### ISSUE TITLE
ER field is not parsed correctly when preceded by a known RefLib field.

### ISSUE THREAD

**Issue by scipilot** [hash-bang/reflib-ris#2]
Hi, I think I've identified a problem in the parse function and I almost have the solution, but not quite.

It seems that the ER field is only parsed correctly when the preceding field happens to be unknown to RefLib. If the preceding field is known, the ER is appended to the preceding field like it's continuing multi-line data. If the reference is re-exported RefLib does add a new ER, but will include these additional ER's from the preceding field resulting in duplicate ER at the end, or if the fields' original order isn't preserved the extra ER might appear in the middle of the reference (Endnote hates that).
 
e.g. The simplest failing test case I've made is:

```
TY  - JOUR
TI  - Test article 1.
DO  - https://dx.doi.org/10.1024/1422-4917/a000447
ER  - 

TY  - JOUR
TI  - Test article 2
AB  - Altered cognitive control and threat processing mediates the relationship between anxiety symptoms and reading problems in children
ER  - 
```

In both of these cases, at `reflib-ris/index.js:129`
```
	var bits = /^(....)- (.*)$/.exec(_.trimEnd(line));
line = "ER  - \n"
bits = null
```
I think the match fails because the trim removes the trailing space which is actually mandated by the regexp. I guess this means it's (unintentionally?) skipping any empty fields.

Then because `bits` is null, it doesn't recognise it as a "field", so it adds it to the previous field at 
`reflib-ris/index.js:175`
```
		ref[refField.reflib] += '\n' + line;
```

This leads to the ER being appended to the DOI and AB respectively:
`DO  - https://dx.doi.org/10.1024/1422-4917/a000447\nER  -`
`AB  - Altered cognitive control and threat processing mediates the relationship between anxiety symptoms and reading problems in children\nER  - `
(this is the output if I re-export it, and which look like random extra ERs if the fields get re-ordered).

The passing test case seems more common in real life.

If the preceding field is not in the `_fieldTranslations` map (like `ID  -`), the difference is `refField` is found to be `null` at line 171, so it skips the append, because `refField` had been nulled at line 169 on the previous iteration. Then somehow it works out that it's the end of the reference anyway (I'm not clear on that part).

Adding an unknown field just before the ER "fixes" the failing import case:

```
TY  - JOUR
TI  - Test article 1.
DO  - https://dx.doi.org/10.1024/1422-4917/a000447
ID  - 2918
ER  - 

TY  - JOUR
TI  - Test article 2
AB  - Altered cognitive control and threat processing mediates the relationship between anxiety symptoms and reading problems in children
ID  - 2919
ER  - 

```

I'm not clear on a proposed solution, as I'm not sure if the "not matching the empty ER field" was by design, so whether there's really two issues interacting to cancel out and work most of the time! It feels like it should have a specific ER detector? 

The PHP version does it differently with an entire reference initially matched like `preg_match_all('!^TY  - (.*?)\n(.*?)^ER  -!ms'` so finding the end is already done. But I can't see this equivalent in the JS.

I will keep looking at it over the coming days and update this issue.

**Comment by scipilot** [comment]
Thanks for reworking it so quickly - I can verify that it's fixed my case.

Strangely though, I just used reflib-cli to test it by importing and exporting a RIS, but it doesn't seem to exhibit the problem anyway (in the output file) in either 1.0.4 nor 1.0.5. However testing inside my app, switching to 1.0.5 definitely fixes it.

**Comment by hash-bang** [comment]
`reflib-cli` uses semver to pull in its child modules (the `reflib-ris` module specifically), so the chances are switching down to `1.0.4` would still pull in the latest RIS module. The downside of Semver I suppose.
